[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn devcatalyst.wsgi:application --bind 0.0.0.0:$PORT"